# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
  
vscode:
  extensions:
    - betterthantomorrow.calva
 
github:
  prebuilds:
    main: true


