# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/

vscode:
  extensions:
    - betterthantomorrow.calva

tasks:
  - name: Prepare deps
    init: sudo apt-get install clojure && y
    command: clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"0.8.3"},cider/cider-nrepl {:mvn/version,"0.26.0"}}}' -P
 
github:
  prebuilds:
    main: true


